spring:
  application:
    name: spring-boot-template
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456789}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9999